// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ku5NRrOVWhNwRHmQRVRc-kMeHej78L4',
    appId: '1:865459250787:web:dc7a0d5fd0db67b2d1fa56',
    messagingSenderId: '865459250787',
    projectId: 'auth-experiment-6e30a',
    authDomain: 'auth-experiment-6e30a.firebaseapp.com',
    storageBucket: 'auth-experiment-6e30a.firebasestorage.app',
    measurementId: 'G-QVZZQFE458',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsIYI09A8mO23e9-_Oczn8gPVRAgOh4Ao',
    appId: '1:865459250787:android:f08bd3dc307478c7d1fa56',
    messagingSenderId: '865459250787',
    projectId: 'auth-experiment-6e30a',
    storageBucket: 'auth-experiment-6e30a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA40z4FuWLPfIF8C0U7qxusbvfHAk70w54',
    appId: '1:865459250787:ios:4ee6ccc7df832603d1fa56',
    messagingSenderId: '865459250787',
    projectId: 'auth-experiment-6e30a',
    storageBucket: 'auth-experiment-6e30a.firebasestorage.app',
    androidClientId: '865459250787-gn2ppj68uoci42ulol0f45dsl7u636pg.apps.googleusercontent.com',
    iosClientId: '865459250787-vu2sqhd1rhnq5o26qgomgk57rfd87o25.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA40z4FuWLPfIF8C0U7qxusbvfHAk70w54',
    appId: '1:865459250787:ios:4ee6ccc7df832603d1fa56',
    messagingSenderId: '865459250787',
    projectId: 'auth-experiment-6e30a',
    storageBucket: 'auth-experiment-6e30a.firebasestorage.app',
    androidClientId: '865459250787-gn2ppj68uoci42ulol0f45dsl7u636pg.apps.googleusercontent.com',
    iosClientId: '865459250787-vu2sqhd1rhnq5o26qgomgk57rfd87o25.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ku5NRrOVWhNwRHmQRVRc-kMeHej78L4',
    appId: '1:865459250787:web:fbff1ea6ac61d7fbd1fa56',
    messagingSenderId: '865459250787',
    projectId: 'auth-experiment-6e30a',
    authDomain: 'auth-experiment-6e30a.firebaseapp.com',
    storageBucket: 'auth-experiment-6e30a.firebasestorage.app',
    measurementId: 'G-MXGN8N5VGY',
  );
}
